### PR TITLE
Pickup requests exclusion dates

### PR DESCRIPTION
**Pull request by lauriek334**
Added new method "arborcat_is_date_location_valid" that can be called by the aadl-ccontent-module to check whether a pickup date and pickup location is valid

### CODE REVIEW

**Comment by lauriek334** [comment]
Note this includes a change to the "arborcat_get_pickup_dates" method. In the associative array of dates returned, it does not just return the 7 pickup dates with exclusion data for each of the dates (if there is any), it now returns an array of pickup dates,  starting the day after the current day, that includes  7 valid pickup dates (ie no exclusion dates) plus any dates that have exclusions.

**Comment by lauriek334** [comment]
Troy, I've reverted the arborcat_get_pickup_dates method to only return information about the days specified by the start_date, end_date parameters

**Comment by taleon** [comment]
arborcat_is_date_location_valid function is broken because it does not pass an end date to arborcat_get_pickup_dates

**Comment by lauriek334** [comment]
arborcat_is_date_location_valid is now restored to working order.

**Pull request merged**
