### PR TITLE
Pickup requests exclusion dates

### PR DESCRIPTION
**Pull request by lauriek334**
Created an arborcat method: arborcat_calculate_pickup_dates
Created new drupal database table: arborcat_pickup_location_exclusion
The arborcat_calculate_pickup_dates method loads the exclusion dates for all library branches from a new database table 'arborcat_pickup_location_exclusion' and is used  by the UserPickupRequest form to seed the pickup date select field
This should be the used by all pickup request forms - it should be simple to use in the uc_summergame prize pickup request form and in the printing and shelfservice web forms to seed the pickup date fields.
Additional work will be needed to support individual location exclusions and will be needed for the november elections at PTS and DTN.

### CODE REVIEW

**Comment by taleon** [comment]
This still shows the pickup date and allows it if you use the branch code or the pickup location id. The only way I was able to prevent scheduling was using 9999

**Comment by lauriek334** [comment]
This  release only supports the district-wide exclusions when a pickup request form is loaded as this is when the possible pickup dates are displayed. I realize that it needs to load the possible pickup dates for a particular location in addition to any district-wide exclusion dates. I have the branch-specific exclusion logic in place and need to do some further testing and possible refactoring to make sure it is working correctly.

**Comment by taleon** [comment]
It would be good to get this all finalized before we roll it out. I thought from your initial message this would be ready for the election exclusions. Those are blocked off anyway, so no need to try to rush anything today.

**Comment by taleon** [comment]
It looks like there's some debugging info in here, merge conflicts that would need to be resolved, and numerous instances of camel case instead of snake case for Drupal variables and function names.

**Comment by lauriek334** [comment]
Debugging removed. 

Camel_case variables and functions changed to snake_case

Revamped the way that the pickup dates are checked for exclusions as follow:
- in BuildForm, the pickup_date select field requires a list of display strings in a key/value array form. To create the options for the select field, a new method: arborcat_get_pickup_dates is called.
- arborcat_get_pickup_dates receives the starting date, ending date and the location as input. It iterates over each of the takes the days of the pickup time period for the user and checks each day for any exclusion data. It returns the display date string for each of the days plus any exclusion data for each day (if there is an exclusion)
- back in BuildForm, the options array is created  by iterating through the returned set of display dates and if there is an exclusion for a particular date, the string ' * not available *' is appended to the end of the date display string.

Removed unreferenced methods from arborcat.module: arborcat_calculate_pickup_dates, arborcat_load_exclusion_data

**Comment by lauriek334** [comment]
FYI - in UserPickupRequstForm.php, lines 130:136 - Added specific check  for end of this shutdown in order to start displaying the 7 valid pickup days starting on Dec 9th 2020 right now.

**Review by ejk — APPROVED** [review]
Looks good. Question of which dates to show in the select drop down on the pickup form, show excluded dates but mark them as disabled? Build a list of dates until we display X dates that are available?

**Comment by lauriek334** [comment]
More thoughts regarding the contents of the pickup date select dropdown menu.
This exclusion dates feature now returns exclusion data along with the formatted date strings and we the question is whether the user should always be presented with 7 valid pickup dates, alonng with excluded dates.  Here's a mockup of two scenarios:
exclusionDateDropDownMockups

**Comment by taleon** [comment]
From a quick pass:

- It looks like the install files for schema are using 4 spaces instead of 2
- We should not be committing debug / testing functionality. Use of kint() would likely handle everything needed during dev and save time having to write out a bunch of test functions and code

With renaming of lots of variables, we should test every step of the process involved here in both scheduling and pickup helper. We can plan to roll this out on the 8th when we'd be reverting the manual dates we have in now.

I haven't looked into it yet, but is there a way to disable one of the select options so it's grayed out, and thus can't even be selected at all? That would be ideal so it doesn't have to get to validation first.

**Comment by lauriek334** [comment]
arborcat.install indentation  issue has been fixed.
only debug-related info is in a comment which I will remove.
I will perform a full set of tests of the pickup request functionality and the pickupHelper functionality over the next couple of days and we should be ready for rollout on the 8th.
I'll look further into disabling of form select field options as I totally agree this would be best from a UI perspective.  There is a module which supports option_attributes in select fields which I'll install and test.

**Comment by taleon** [comment]
There are references to dblog in the pickup_test function. Not a huge deal; just trying to keep commits clean and with functional code that is actually used in production.

**Pull request merged**
